laba1/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace laba1.Models
{
    public class Category
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        public virtual ICollection<Service> Services { get; set; }
    }
}

laba1/Models/Service.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace laba1.Models
{
    public class Service
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        public string Description { get; set; }

        public int? CategoryId { get; set; }
        public virtual Category Category { get; set; }
    }
}

laba1/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using laba1.DataAccessLevel;
using laba1.Models;
using laba1.DataAccessLevel;

namespace laba1.Controllers
{
    public class CategoryController : Controller
    {
        CategoryDataAccess CategoryDA = new CategoryDataAccess();

        public ActionResult Index()
        {
            return View(CategoryDA.getAllTeams());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category Category = CategoryDA.getParticularCategory(id);
            if (Category == null)
            {
                return HttpNotFound();
            }
            return View(Category);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title")] Category Category) 
        {
            try
            {
                if (ModelState.IsValid)
                {
                    CategoryDA.Add(Category);
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(Category);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                CategoryDA.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

laba1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace laba1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

laba1/Controllers/ServiceController.cs
using System.Net;
using System.Web.Mvc;
using laba1.DataAccessLevel;
using laba1.Models;
using System;

namespace laba1.Controllers
{
    public class ServiceController : Controller
    {
        private SampleContext db = new SampleContext();

        ServiceDataAccess serviceDA = new ServiceDataAccess();

        public ActionResult Index()
        {
            return View(serviceDA.getAllServices());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = serviceDA.getService(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categorys, "Id", "Title");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Description")] Service service)
        {
            if (ModelState.IsValid)
            {
                db.Services.Add(service);
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categorys, "Id", "Title", service.CategoryId);
            return View(service);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = db.Services.Find(id);
            ViewBag.myid = service.CategoryId;
            if (service == null)
            {
                return HttpNotFound();
                
            }
           
            ViewBag.CategoryId = new SelectList(db.Categorys, "Id", "Title", service.CategoryId);
            return View(service);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title, Description, CategoryId")] Service service)
        {
            if (ModelState.IsValid)
            {
                serviceDA.Update(service);
                return RedirectToAction("Index");
            }
            ViewBag.TeamId = new SelectList(db.Categorys, "Id", "Title", service.CategoryId);

            return View(service);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = serviceDA.getService(id);

            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            serviceDA.DeleteService(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                serviceDA.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

laba1/Views/Category/Create.cshtml
@model laba1.Models.Category

@{
    ViewBag.Title = "Создание";
}

<h2>Создание</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Категория</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку категорий", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

laba1/Views/Category/Details.cshtml
@model laba1.Models.Category

@{
    ViewBag.Title = "Подробнее";
}

<h2>Подробности о категории</h2>

<div>
    <h4>Команда</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        

        @if (Model.Services.Count != 0)
        {
            <dt>
                Услуги в категории
            </dt>
        
            <dd>
                <ul class="list-group">

                    @foreach (var item in Model.Services)
                    {
                    <li class="list-group-item">@Html.DisplayFor(modelItem => item.Title) – 
                                                @Html.DisplayFor(modelItem => item.Description)</li>

                    }
                </ul>
            </dd>
        }
        else
        {
            <dd>
                No such service!
            </dd>
        }

    </dl>
</div>
<p>
    @Html.ActionLink("Назад к списку категорий", "Index")
</p>

laba1/Views/Category/Index.cshtml
@model IEnumerable<laba1.Models.Category>

@{
    ViewBag.Title = "Index";
}

<h2>Категории</h2>

<p>
    @Html.ActionLink("Добавить категорию", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.ActionLink("Подробности", "Details", new { id=item.Id })
        </td>
    </tr>
}

</table>

laba1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

laba1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

laba1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Юридические услуги</h1>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Лаба 1</h2>
        <p>
            Law services

            Сущности две: категории и услуги. У категории множество услуг, у услуг одна категория.
        </p>
    </div>

</div>

laba1/Views/Service/Create.cshtml
@model laba1.Models.Service

@{
    ViewBag.Title = "Create";
}

<h2>Создание</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Услуги</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "Категория", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку всех услуг", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

laba1/Views/Service/Delete.cshtml
@model laba1.Models.Service

@{
    ViewBag.Title = "Delete";
}

<h2>Удаление</h2>

<h3>Вы уверены что хотите удалить эту услуги?</h3>
<div>
    <h4>Услуга</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-danger"/> |
            @Html.ActionLink("Назад к списку всех услуг", "Index")
        </div>
    }
</div>

laba1/Views/Service/Details.cshtml
@model laba1.Models.Service

@{
    ViewBag.Title = "Details";
}

<h2>Подробности</h2>

<div>
    <h4>Категория</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Назад к списку всех категорий", "Index")
</p>

laba1/Views/Service/Edit.cshtml
@model laba1.Models.Service

@{
    ViewBag.Title = "Edit";
}

<h2>Редактирование</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Услуга</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
      

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "Категория", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку всех услуг", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

laba1/Views/Service/Index.cshtml
@model IEnumerable<laba1.Models.Service>

@{
    ViewBag.Title = "Index";
}

<h2>Услуги</h2>

<p>
    @Html.ActionLink("Создать новую услугу", "Create")
</p>
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        
        <th>
            Категория
        </th>
        

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Title)
        </td>
        <td>
            @Html.ActionLink("Редактировать", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Подробности", "Details", new { id=item.Id }) |
            @Html.ActionLink("Удалить", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

laba1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – Teams and players</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Law service", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Services", "Index", "Service")</li>
                    <li>@Html.ActionLink("Categorys", "Index", "Category")</li>
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – Law services</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>